rest-template:
  connection-pool:
    max-total: 40
    max-per-route: 20
    idle-connection-timeout-seconds: 30  # Previously hardcoded in RestTemplateConfig
    validate-after-inactivity-seconds: 1  # For future use, previously commented out
  timeout:
    connection: 10000
    read: 120000
    connection-request: 5000
  compression:
    enabled: true  # Enable gzip compression for large payloads
    min-request-size: 1024  # Only compress requests larger than 1KB
  headers:
    default-content-type: "application/json"  # Previously hardcoded in tavilyClient
  logging:
    enabled: true  # Enable compression and connection pool logging

# Tika OCR Configuration
tika:
  ocr:
    enabled: true
    language: "eng+spa"  # Support both English and Spanish
    confidence-threshold: 70
    page-segmentation-mode: 1  # Automatic page segmentation with OSD
    timeout-seconds: 120
    max-file-size-mb: 5  # Maximum file size for OCR processing
    enable-image-preprocessing: true
    render-dpi: 300
    ocr-strategy: "OCR_AND_TEXT_EXTRACTION"
    extract-inline-images: true
    write-limit: 100000
  file:
    max-size-mb: 5  # Maximum file size for processing
    temp-dir: "/tmp/conversion"  # Temporary directory for file processing

# Google Vision API Configuration
google:
  vision:
    enabled: true
    confidence-threshold: 85  # Use Google Vision if Tika confidence < 85%
    project-id: ${GOOGLE_CLOUD_PROJECT_ID:}
    credentials-path: ${GOOGLE_APPLICATION_CREDENTIALS:}
    max-file-size-mb: 5
    timeout-seconds: 30
    language-hints: ["en", "es"]
    enable-text-detection: true
    enable-document-text-detection: true

# Legacy conversion settings (for backward compatibility)
conversion:
  logging:
    enabled: true  # Enable conversion process logging
