rest-template:
  connection-pool:
    max-total: 40
    max-per-route: 20
    idle-connection-timeout-seconds: 30  # Previously hardcoded in RestTemplateConfig
    validate-after-inactivity-seconds: 1  # For future use, previously commented out
  timeout:
    connection: 10000
    read: 120000
    connection-request: 5000
  compression:
    enabled: true  # Enable gzip compression for large payloads
    min-request-size: 1024  # Only compress requests larger than 1KB
  headers:
    default-content-type: "application/json"  # Previously hardcoded in tavilyClient
  logging:
    enabled: true  # Enable compression and connection pool logging

conversion:
  ocr:
    languages: "eng+spa"  # Support both English and Spanish
    enabled: true
    confidence-threshold: 60
    page-segmentation-mode: 1  # Automatic page segmentation with OSD
  tika:
    enabled: true
    max-string-length: 100000  # Maximum text length to extract
    timeout-seconds: 30
  pdfbox:
    enabled: true
    dpi: 300  # DPI for image extraction from PDF
    image-type: "png"
  file:
    max-size-mb: 4  # Maximum file size for processing
    temp-dir: "/tmp/conversion"  # Temporary directory for file processing
  logging:
    enabled: true  # Enable conversion process logging
